name: snapcraft_launcher
description: A native Dart client library to access the snapd desktop-launch interface.
version: 0.1.0
repository: https://github.com/d-loose/snapcraft_launcher.dart

environment:
  sdk: '>=2.18.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.8
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0